#!/bin/bash

# Script to auto build and install vsearch Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building vsearch ${VERSION} on ${DATE}"
cd /opt/bioit/vsearch/src
#wget https://github.com/torognes/vsearch/archive/${VERSION}.tar.gz
wget https://github.com/torognes/vsearch/archive/v${VERSION}.tar.gz
#mv ${VERSION}.tar.gz vsearch-${VERSION}.tar.gz
mv v${VERSION}.tar.gz vsearch-${VERSION}.tar.gz
tar xvf vsearch-${VERSION}.tar.gz
cd vsearch-${VERSION}
./autogen.sh
./configure --prefix=/opt/bioit/vsearch/${VERSION}
# Building native can produce binaries that don't work on all x86-64 machines
sed -i -e 's/native/x86-64/g' Makefile src/Makefile
make -j8
make install
echo "Writing modulefile"
echo "#%Module 1.0
#
#  tophat module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/vsearch/${VERSION}/bin 
prepend-path  MANPATH           /opt/bioit/vsearch/${VERSION}/share/man" > /opt/bioit/modulefiles/vsearch/${VERSION}
echo "Writing module .version to set default"
echo "#%Module1.0
##
##  The desired version of vsearch
##
set ModulesVersion ${VERSION}" > /opt/bioit/modulefiles/vsearch/.version
