# Mount points for bioit common data
- name: Mount for bioit executables
  mount: state=mounted src=silver:/opt/bioit path=/opt/bioit fstype=nfs opts="defaults"

#- name: Mount for biological databases
  #mount: state=mounted src=adenine:/export/nas/databases path=/databases fstype=nfs

# - name: Install package for SELinux control
  # yum: name=libsemanage-python state=present

# - name: Update SELinux for NFS homes
  # seboolean: name=use_nfs_home_dirs persistent=yes state=yes

- name: Mount for homes
  mount: state=mounted src=silver:/home path=/home fstype=nfs opts="defaults"
