install.packages(c('ape', 'optparse', 'RColorBrewer', 'randomForest', 'vegan'))
# install.packages("biom") # Removed from CRAN
install.packages("base64")
install.packages("gplots")
install.packages("ggplot2")
install.packages("scales")
install.packages("gsalib")
install.packages("reshape")
install.packages("statmod")
install.packages("akima")
install.packages("gam")
install.packages("mvtnorm")
install.packages("RUnit")
install.packages("plotrix")
install.packages("devtools")
install.packages("HiddenMarkov")
install.packages("locfdr")
install.packages("BH")
install.packages("brew")
install.packages("roxygen2")
install.packages("rversions")
install.packages("xml2")
# install.packages("JSONIO") # not available for R-3.4.1
# install.packages("http://cran.r-project.org/src/contrib/Archive/locfdr/locfdr_1.1-7.tar.gz", repos = NULL, type="source")
install.packages("optparse")
install.packages("colorfulVennPlot")
install.packages("gridBase")
install.packages("ascii")
install.packages("aws")
install.packages("awsMethods")
install.packages("chron")
install.packages("corpcor")
install.packages("formatR")
install.packages("gsl")
install.packages("gsmoothr")
install.packages("gsubfn")
install.packages("highr")
install.packages("knitr")
install.packages("markdown")
install.packages("mime")
install.packages("png")
install.packages("RH2")
install.packages("rJava")
install.packages("RJDBC")
install.packages("RMySQL")
install.packages("RPostgreSQL")
install.packages("haplo.stats")
install.packages("https://cran.r-project.org/src/contrib/Archive/RcppArmadillo/RcppArmadillo_0.6.600.4.0.tar.gz", repos=NULL, type="source")

### BioC Packages for R.
source("http://www.bioconductor.org/biocLite.R")
biocLite()
biocLite("affyQCReport")
biocLite("ROTS")
biocLite("goseq")
biocLite("ShortRead")
biocLite("biomaRt")
biocLite("DESeq")
biocLite(c('DESeq2', 'metagenomeSeq'))
biocLite("DNAcopy")
biocLite("aroma.light")
biocLite("affxparser")
biocLite("edgeR")
biocLite("xps")
biocLite("ctc")
biocLite("ape")
biocLite("GenomeGraphs")
biocLite("limma")
biocLite("pcot2")
biocLite("HilbertVis")
biocLite("cummeRbund")
biocLite("multtest")
biocLite("Genominator")
biocLite("sva")
biocLite("BSgenome.Hsapiens.UCSC.hg19")
biocLite("BSgenome.Mmusculus.UCSC.mm10")
biocLite("bumphunter")
biocLite("impute") 
biocLite("KEGG.db")
biocLite("safe")
biocLite("org.Hs.eg.db")
biocLite(c("GO.db", "preprocessCore"))
biocLite("methylKit")

install.packages("WGCNA")

library(devtools)
#### locfdr removed from CRAN so may have to grab source manually to build
#### this until they update their package
#install_github('alyssafrazee/derfinder')
biocLite("derfinder")

#### This section doesn't work for R2
#source("http://aroma-project.org/hbLite.R")
#hbInstall("aroma.affymetrix")
#source('http://callr.org/install#aroma.affymetrix')
install.packages("aroma.core")
install.packages("aroma.apd")
install.packages("aroma.affymetrix")
#install.packages("https://cran.r-project.org/src/contrib/aroma.affymetrix_2.13.2.tar.gz", repos = NULL, type="source")
