install.packages(c('ape', 'optparse', 'RColorBrewer', 'randomForest', 'vegan'),repos="https://cloud.r-project.org/")
# install.packages("biom") # Removed from CRAN
install.packages("base64",repos="https://cloud.r-project.org/")
install.packages("gplots",repos="https://cloud.r-project.org/")
install.packages("ggplot2",repos="https://cloud.r-project.org/")
install.packages("scales",repos="https://cloud.r-project.org/")
install.packages("gsalib",repos="https://cloud.r-project.org/")
install.packages("reshape",repos="https://cloud.r-project.org/")
install.packages("statmod",repos="https://cloud.r-project.org/")
install.packages("akima",repos="https://cloud.r-project.org/")
install.packages("gam",repos="https://cloud.r-project.org/")
install.packages("mvtnorm",repos="https://cloud.r-project.org/")
install.packages("RUnit",repos="https://cloud.r-project.org/")
install.packages("plotrix",repos="https://cloud.r-project.org/")
install.packages("devtools",repos="https://cloud.r-project.org/")
install.packages("HiddenMarkov",repos="https://cloud.r-project.org/")
install.packages("locfdr",repos="https://cloud.r-project.org/")
install.packages("BH",repos="https://cloud.r-project.org/")
install.packages("brew",repos="https://cloud.r-project.org/")
install.packages("roxygen2",repos="https://cloud.r-project.org/")
install.packages("rversions",repos="https://cloud.r-project.org/")
install.packages("xml2",repos="https://cloud.r-project.org/")
# install.packages("JSONIO") # not available for R-3.4.1
# install.packages("http://cran.r-project.org/src/contrib/Archive/locfdr/locfdr_1.1-7.tar.gz", repos = NULL, type="source")
install.packages("optparse",repos="https://cloud.r-project.org/")
install.packages("colorfulVennPlot",repos="https://cloud.r-project.org/")
install.packages("gridBase",repos="https://cloud.r-project.org/")
install.packages("ascii",repos="https://cloud.r-project.org/")
install.packages("aws",repos="https://cloud.r-project.org/")
install.packages("awsMethods",repos="https://cloud.r-project.org/")
install.packages("chron",repos="https://cloud.r-project.org/")
install.packages("corpcor",repos="https://cloud.r-project.org/")
install.packages("formatR",repos="https://cloud.r-project.org/")
install.packages("gsl",repos="https://cloud.r-project.org/")
install.packages("gsmoothr",repos="https://cloud.r-project.org/")
install.packages("gsubfn",repos="https://cloud.r-project.org/")
install.packages("highr",repos="https://cloud.r-project.org/")
install.packages("knitr",repos="https://cloud.r-project.org/")
install.packages("markdown",repos="https://cloud.r-project.org/")
install.packages("mime",repos="https://cloud.r-project.org/")
install.packages("png",repos="https://cloud.r-project.org/")
install.packages("RH2",repos="https://cloud.r-project.org/")
install.packages("rJava",repos="https://cloud.r-project.org/")
install.packages("RJDBC",repos="https://cloud.r-project.org/")
install.packages("RMySQL",repos="https://cloud.r-project.org/")
install.packages("RPostgreSQL",repos="https://cloud.r-project.org/")
install.packages("haplo.stats",repos="https://cloud.r-project.org/")
install.packages("RcppArmadillo",repos="https://cloud.r-project.org/")
install.packages("mvtnorm",repos="https://cloud.r-project.org/")
install.packages("modeltools",repos="https://cloud.r-project.org/")
install.packages("coin",repos="https://cloud.r-project.org/")
install.packages("MASS",repos="https://cloud.r-project.org/")

### BioC Packages for R.
install.packages("BiocManager",repos="https://cloud.r-project.org/")
BiocManager::install()
BiocManager::install("affyQCReport")
BiocManager::install("ROTS")
BiocManager::install("goseq")
BiocManager::install("ShortRead")
BiocManager::install("biomaRt")
BiocManager::install("DESeq")
BiocManager::install(c('DESeq2', 'metagenomeSeq'))
BiocManager::install("DNAcopy")
BiocManager::install("aroma.light")
BiocManager::install("affxparser")
BiocManager::install("edgeR")
BiocManager::install("xps")
BiocManager::install("ctc")
BiocManager::install("ape")
BiocManager::install("GenomeGraphs")
BiocManager::install("limma")
BiocManager::install("pcot2")
BiocManager::install("HilbertVis")
BiocManager::install("cummeRbund")
BiocManager::install("multtest")
BiocManager::install("Genominator")
BiocManager::install("sva")
BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")
BiocManager::install("BSgenome.Mmusculus.UCSC.mm10")
BiocManager::install("bumphunter")
BiocManager::install("impute") 
BiocManager::install("KEGG.db")
BiocManager::install("safe")
BiocManager::install("org.Hs.eg.db")
BiocManager::install(c("GO.db", "preprocessCore"))
BiocManager::install("methylKit")

install.packages("WGCNA",repos="https://cloud.r-project.org/")

library(devtools)
#### locfdr removed from CRAN so may have to grab source manually to build
#### this until they update their package
#install_github('alyssafrazee/derfinder')
BiocManager::install("derfinder")

#### This section doesn't work for R2
#source("http://aroma-project.org/hbLite.R")
#hbInstall("aroma.affymetrix")
#source('http://callr.org/install#aroma.affymetrix')
install.packages("aroma.core",repos="https://cloud.r-project.org/")
install.packages("aroma.apd",repos="https://cloud.r-project.org/")
install.packages("aroma.affymetrix",repos="https://cloud.r-project.org/")
#install.packages("https://cran.r-project.org/src/contrib/aroma.affymetrix_2.13.2.tar.gz", repos = NULL, type="source")
