#!/bin/bash

# Script to auto build and install medaka. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

APP="medaka"
VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building ${APP} ${VERSION} on ${DATE}"

# Create install directory
mkdir -p /opt/bioit/${APP}/${VERSION}/bin
cd /opt/bioit/${APP}/${VERSION}/
apptainer pull docker://ontresearch/medaka:latest
mv medaka_latest.sif medaka_${VERSION}.sif
# Create version specific template
# Create scripts to run each binary in container
echo "#!/bin/bash

name=\${0##*/}
export LC_ALL=C
singularity --silent exec --bind /raid /opt/bioit/medaka/${VERSION}/medaka_${VERSION}.sif \$name \"\$@\""  > /opt/bioit/${APP}/${VERSION}/bin/medaka
cp /opt/bioit/${APP}/${VERSION}/bin/medaka /opt/bioit/${APP}/${VERSION}/bin/medaka_consensus

# Make all scripts executable
chmod a+x /opt/bioit/${APP}/${VERSION}/bin/*

echo "Writing modulefile"
echo "#%Module 1.0
#
#  ${APP} module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/${APP}/${VERSION}/bin" > /opt/bioit/modulefiles/${APP}/${VERSION}
echo "Writing module .version to set default"
echo "#%Module1.0
##
##  The desired version of ${APP}
##
set ModulesVersion ${VERSION}" > /opt/bioit/modulefiles/${APP}/.version
