#!/bin/bash
set -e

# Script to auto build and install medaka. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

APP="medaka"
VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building ${APP} ${VERSION} on ${DATE}"

# Create install directory
mkdir -p /opt/bioit/${APP}/${VERSION}/bin
# Build container def from template by adding version in
#sed -e "s%VERSION%${VERSION}%g" ${HOME}/bioit/apps/${APP}/SPEC/ubuntu_${APP}.def_template > ${HOME}/bioit/apps/${APP}/SPEC/ubuntu_${APP}_${VERSION}.def
${HOME}/bioit/bin/create_singularity_conda_env.py3 -u -a ${APP} -v ${VERSION} -l /opt/bioit/${APP}/${VERSION}
# build container
#apptainer build --fakeroot /opt/bioit/${APP}/${VERSION}/${APP}_${VERSION}.sif ${HOME}/bioit/apps/${APP}/SPEC/ubuntu_${APP}_${VERSION}.def
apptainer build --fakeroot /opt/bioit/${APP}/${VERSION}/${APP}_${VERSION}.sif /opt/bioit/${APP}/${VERSION}/Singularity
# remove the def file to clean up
#rm ${HOME}/bioit/apps/${APP}/SPEC/ubuntu_${APP}_${VERSION}.def
# Create version specific template
sed -e "s%APPVER%${APP}_${VERSION}%g" ${HOME}/bioit/bin/bin_template > ${APP}_bin_template
sed -i "s%APPNAME%${APP}%g" ${APP}_bin_template
sed -i "s%VERSION%${VERSION}%g" ${APP}_bin_template
sed -i "s%BINDS%/raid%g" ${APP}_bin_template
#sed -i "s%BINDS%/raid,/active,/archive,/data,/databases,/deepgene,/dunninga,/gbs_pine,/scratch,/sequencing,/treestem%g" ${APP}_bin_template
sed -i "s%EXEC%micromamba run -p /opt/conda/envs/${APP}_${VERSION}_singularity%g" ${APP}_bin_template
#sed -i "s%EXEC %%g" ${APP}_bin_template

# Create scripts to run each binary in container
cat ${APP}_bin_template > /opt/bioit/${APP}/${VERSION}/bin/medaka
cat ${APP}_bin_template > /opt/bioit/${APP}/${VERSION}/bin/medaka_consensus
cat ${APP}_bin_template > /opt/bioit/${APP}/${VERSION}/bin/medaka_haploid_variant
cat ${APP}_bin_template > /opt/bioit/${APP}/${VERSION}/bin/mini_align

# Make all scripts executable
chmod a+x /opt/bioit/${APP}/${VERSION}/bin/*
# Remove the versioned template
rm ${APP}_bin_template

echo "Writing modulefile"
echo "#%Module 1.0
#
#  ${APP} module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/${APP}/${VERSION}/bin" > /opt/bioit/modulefiles/${APP}/${VERSION}
echo "Writing module .version to set default"
echo "#%Module1.0
##
##  The desired version of ${APP}
##
set ModulesVersion ${VERSION}" > /opt/bioit/modulefiles/${APP}/.version
