#!/bin/bash

# Script to auto build and install abyss Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building abyss ${VERSION} on ${DATE}"
cd /opt/bioit/abyss/src
wget https://github.com/bcgsc/abyss/releases/download/${VERSION}/abyss-${VERSION}.tar.gz
#wget --no-check-certificate https://github.com/bcgsc/abyss/releases/download/${VERSION}/abyss-${VERSION}.tar.gz
tar xvf abyss-${VERSION}.tar.gz
cd abyss-${VERSION}
# Requires specific version of boost
wget http://sourceforge.net/projects/boost/files/boost/1.56.0/boost_1_56_0.tar.bz2
#wget --no-check-certificate http://sourceforge.net/projects/boost/files/boost/1.56.0/boost_1_56_0.tar.bz2
tar xvf boost_1_56_0.tar.bz2
./configure --prefix=/opt/bioit/abyss/${VERSION}
make clean
make
make install
cd /opt/bioit/abyss/${VERSION}/bin
# Some scripts expect ABYSS-P so fake it for them
ln -sf ABYSS ABYSS-P
echo "Writing modulefile"
echo "#%Module 1.0
#
#  abyss module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/abyss/${VERSION}/bin
prepend-path  MANPATH           /opt/bioit/abyss/${VERSION}/share/man/man1" > /opt/bioit/modulefiles/abyss/${VERSION}
