#!/bin/bash

# Script to auto build and install abyss Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building abyss ${VERSION} on ${DATE}"

# Create install directory
mkdir -p /opt/bioit/abyss/${VERSION}/bin
# Generate Singularity def file
../../../bin/create_singularity_conda_env.py3 -a abyss -v ${VERSION} -l /opt/bioit/abyss/${VERSION}
# Build container
singularity build --fakeroot /opt/bioit/abyss/${VERSION}/abyss_${VERSION}.sif /opt/bioit/abyss/${VERSION}/Singularity
sh ./make_bins ${VERSION}

echo "Writing modulefile"
echo "#%Module 1.0
#
#  abyss module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/abyss/${VERSION}/bin" > /opt/bioit/modulefiles/abyss/${VERSION}
echo "Writing module .version to set default"
echo "#%Module1.0
##
##  The desired version of abyss
##
set ModulesVersion ${VERSION}" > /opt/bioit/modulefiles/abyss/.version
