#!/bin/bash
set -e

# Script to auto build and install augustus Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building augustus ${VERSION} on ${DATE}"
cd /opt/bioit/augustus/src
wget http://bioinf.uni-greifswald.de/augustus/binaries/augustus-${VERSION}.tar.gz
tar xvf augustus-${VERSION}.tar.gz
#mv augustus augustus-${VERSION}
cd augustus-${VERSION}
make clean
# Grab bamtools dependency
echo "Getting and installing bamtools dependency"
wget https://github.com/pezmaster31/bamtools/archive/v2.5.1.tar.gz
tar xvf v2.5.1.tar.gz
cd bamtools-2.5.1
mkdir build
cd build
cmake3 -DCMAKE_INSTALL_PREFIX:PATH=/opt/bioit/augustus/src/augustus-${VERSION}/bamtools ..
make all
make install
cd /opt/bioit/augustus/src/augustus-${VERSION}
# patch bam2hints Makefile
sed "s+INCLUDES = -I/usr/include/bamtools+INCLUDES = -I/opt/bioit/augustus/src/augustus-${VERSION}/bamtools/include/bamtools+" --in-place auxprogs/bam2hints/Makefile
sed "s+LIBS = -lbamtools -lz+LIBS = /opt/bioit/augustus/src/augustus-${VERSION}/bamtools/lib64/libbamtools.a -lz+" --in-place auxprogs/bam2hints/Makefile
# patch filterBam Makefile
sed "s+BAMTOOLS = /usr/include/bamtools+BAMTOOLS = /opt/bioit/augustus/src/augustus-${VERSION}/bamtools+" --in-place auxprogs/filterBam/src/Makefile
sed "s+INCLUDES = -I\$(BAMTOOLS) -Iheaders -I./bamtools+INCLUDES = -I\$(BAMTOOLS)/include/bamtools -Iheaders -I./bamtools+" --in-place auxprogs/filterBam/src/Makefile
sed "s+LIBS = -lbamtools -lz+LIBS = \$(BAMTOOLS)/lib64/libbamtools.a -lz+" --in-place auxprogs/filterBam/src/Makefile
# patch bam2wig Makefile
sed "s+TOOLDIR=\$(HOME)/tools+TOOLDIR=/opt/bioit/augustus/src/augustus-${VERSION}+" --in-place auxprogs/bam2wig/Makefile
#sed "s+LIBS=\$(SAMTOOLS)/libbam.a \$(HTSLIB)/libhts.a -lcurses -lm -lz -lpthread+LIBS=\$(SAMTOOLS)/libbam.a \$(HTSLIB)/libhts.a -lcurses -lm -lz -lpthread -lcurl -lcrypto+" --in-place auxprogs/bam2wig/Makefile
# patch Makefile to set install directory
sed "s+INSTALLDIR = /opt/augustus-\$(AUGVERSION)+INSTALLDIR = /opt/bioit/augustus/${VERSION}+" --in-place Makefile
# Remove symlinks lines to avoid permission denied error
sed '/ln /d' --in-place Makefile
# Build dependencies for bam2wig
echo "Getting htslib"
#git clone https://github.com/samtools/htslib.git
wget https://github.com/samtools/htslib/releases/download/1.11/htslib-1.11.tar.bz2
tar xvf htslib-1.11.tar.bz2
cd htslib-1.11
autoheader
autoconf
./configure
make
cd ..
ln -s htslib-1.11 htslib
echo "Getting bcftools"
#git clone https://github.com/samtools/bcftools.git
wget https://github.com/samtools/bcftools/releases/download/1.11/bcftools-1.11.tar.bz2
tar xvf bcftools-1.11.tar.bz2
cd bcftools-1.11
autoheader
autoconf
./configure
make
cd ..
ln -s bcftools-1.11 bcftools
echo "Getting samtools"
# git clone https://github.com/samtools/samtools.git
wget https://github.com/samtools/samtools/releases/download/1.11/samtools-1.11.tar.bz2
tar xvf samtools-1.11.tar.bz2
cd samtools-1.11
autoheader
autoconf -Wno-syntax
./configure
make
cd ..
ln -s samtools-1.11 samtools
export TOOLDIR=`pwd`
# Now build augustus
# Turn off comparative gene prediction
#sed "s+COMPGENEPRED = true+COMPGENEPRED = false+" --in-place common.mk
# Turn off MYSQL support because it doesn't work on RL8
echo "MYSQL = false" >> common.mk
make
make install
# Augustus build misses utrrnaseq bin for some reason
cp auxprogs/utrrnaseq/Debug/utrrnaseq /opt/bioit/augustus/${VERSION}/bin
# Fix directory and file permissions after install
find /opt/bioit/augustus/${VERSION} -type d -exec chmod a+rx {} +
find /opt/bioit/augustus/${VERSION} -type f -exec chmod a+r {} +
echo "Writing modulefile"
echo "#%Module 1.0
#
#  augustus module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/augustus/${VERSION}/bin:/opt/bioit/augustus/${VERSION}/scripts" > /opt/bioit/modulefiles/augustus/${VERSION}
echo "Writing module .version to set default"
echo "#%Module1.0
##
##  The desired version of augustus
##
set ModulesVersion ${VERSION}" > /opt/bioit/modulefiles/augustus/.version
