rpmbuild -bb /opt/biology/bamtools/SPEC/bamtools.spec
rpmbuild -bb /opt/biology/bbmap/SPEC/bbmap.spec
rpmbuild -bb /opt/biology/bcftools/SPEC/bcftools.spec
rpmbuild -bb /opt/biology/bedtools2/SPEC/bedtools2.spec
rpmbuild -bb /opt/biology/bowtie2/SPEC/bowtie2.spec
rpmbuild -bb /opt/biology/bowtie/SPEC/bowtie.spec
rpmbuild -bb /opt/biology/bwa/SPEC/bwa.spec
rpmbuild -bb /opt/biology/FastQC/SPEC/FastQC.spec
rpmbuild -bb /opt/biology/hisat2/SPEC/hisat2.spec
rpmbuild -bb /opt/biology/htslib/SPEC/htslib.spec
rpmbuild -bb /opt/biology/ncbi-blast/SPEC/ncbi-blast.spec
rpmbuild -bb /opt/biology/R-core/SPEC/R-core.spec
rpmbuild -bb /opt/biology/samtools/SPEC/samtools.spec
rpmbuild -bb /opt/biology/SOAPdenovo2/SPEC/SOAPdenovo2.spec
rpmbuild -bb /opt/biology/SolexaQA++/SPEC/SolexaQA++.spec
rpmbuild -bb /opt/biology/tophat2/SPEC/tophat2.spec
rpmbuild -bb /opt/biology/vcftools/SPEC/vcftools.spec
