#!/bin/bash

# rm coverage.hist test*

set -e

# abyss-pe k=25 name=test in='reads1.fastq reads2.fastq'
abyss-pe np=4 mpirun="/usr/lib64/openmpi/bin/mpirun --allow-run-as-root" k=25 name=test in='reads1.fastq reads2.fastq'

cmp -s reference-stats.md test-stats.md > /dev/null
if [ $? -eq 1 ]; then
  exit 1
fi

rm coverage.hist test*

exit 0
