#!/bin/bash

# Script to auto build and install bamtools. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building vcftools ${VERSION} on ${DATE}"
cd /opt/bioit/vcftools/src
wget https://github.com/vcftools/vcftools/releases/download/v${VERSION}/vcftools-${VERSION}.tar.gz
tar xvf vcftools-${VERSION}.tar.gz
cd vcftools-${VERSION}
./configure --prefix=/opt/bioit/vcftools/${VERSION}
make
make install
cd /opt/bioit/vcftools/${VERSION}/bin
sed "s+use strict;+use lib '/opt/bioit/vcftools/${VERSION}/share/perl5'; use strict;+" --in-place *
echo "Writing modulefile"
echo "#%Module 1.0
#
#  tophat module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/vcftools/${VERSION}/bin 
prepend-path  MANPATH           /opt/bioit/vcftools/${VERSION}/share/man" > /opt/bioit/modulefiles/vcftools/${VERSION}
