#!/bin/bash
set -e

# Script to auto build and install bwa. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
NUMBERS=${VERSION%%[A-Za-z]*}
DATE=`date +"%d/%m/%Y %r"`
echo "Building bwa ${VERSION} on ${DATE}"
cd /opt/bioit/bwa/src
wget https://github.com/lh3/bwa/releases/download/v${NUMBERS}/bwa-${VERSION}.tar.bz2
tar xvf bwa-${VERSION}.tar.bz2
cd bwa-${VERSION}
make CC='gcc -fcommon'
mkdir -p /opt/bioit/bwa/${VERSION}/bin
mkdir -p /opt/bioit/bwa/${VERSION}/man/man1
mv bwa /opt/bioit/bwa/${VERSION}/bin/
mv *.pl /opt/bioit/bwa/${VERSION}/bin
mv bwa.1 /opt/bioit/bwa/${VERSION}/man/man1/

echo "Writing modulefile"
echo "#%Module 1.0
#
#  bwa module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/bwa/${VERSION}/bin
prepend-path  MANPATH           /opt/bioit/bwa/${VERSION}/man" > /opt/bioit/modulefiles/bwa/${VERSION}
echo "Writing module .version to set default"
echo "#%Module1.0
##
##  The desired version of bwa
##
set ModulesVersion ${VERSION}" > /opt/bioit/modulefiles/bwa/.version
