# Mount points for bioit common data
- name: Mount for bioit executables
  mount: state=mounted src=nfs:/opt/bioit path=/opt/bioit fstype=nfs opts="defaults"

- name: Mount for biological databases
  mount: state=mounted src=adenine:/export/nas/databases path=/databases fstype=nfs

- name: Install package for SELinux control
  yum: name=libsemanage-python state=present

- name: Update SELinux for NFS homes
  seboolean: name=use_nfs_home_dirs persistent=yes state=yes

- name: Mount for homes
  mount: state=mounted src=nfs:/home path=/home fstype=nfs opts="defaults"

# Mounts for MasseyIFS
- name: Mount for massey-ifs-group scratch
  mount: state=absent src=nfs:/scratch/massey-ifs-group path=/scratch/massey-ifs-group fstype=nfs opts="defaults"

- name: Mount for massey-ifs-group work
  mount: state=absent src=nfs:/work/massey-ifs-group path=/work/massey-ifs-group fstype=nfs opts="defaults"

- name: Mount for massey-ifs-group sequencing
  mount: state=absent src=nfs:/sequencing/massey-ifs-group path=/sequencing/massey-ifs-group fstype=nfs opts="defaults"

# Mounts for RTG R&D
- name: Mount for rtgrnd scratch
  mount: state=mounted src=nfs:/scratch/rtgrnd path=/scratch/rtgrnd fstype=nfs opts="defaults"

- name: Mount for rtgrnd work
  mount: state=mounted src=nfs:/work/rtgrnd path=/work/rtgrnd fstype=nfs opts="defaults"

- name: Mount for rtgrnd sequencing
  mount: state=mounted src=nfs:/sequencing/rtgrnd path=/sequencing/rtgrnd fstype=nfs opts="defaults"

# Create symlinks

- file: src=/work dest=/active state=link
- file: src=/sequencing dest=/archive state=link
