# Mount points for bioit common data
- name: Mount for bioit executables
  mount: state=mounted src=chips:/opt/bioit path=/opt/bioit fstype=nfs

- name: Mount for biological databases
  mount: state=mounted src=adenine:/export/nas/databases path=/databases fstype=nfs

- name: Install package for SELinux control
  yum: name=libsemanage-python state=present

- name: Update SELinux for NFS homes
  seboolean: name=use_nfs_home_dirs persistent=yes state=yes

- name: Mount for homes
  mount: state=mounted src=chips:/home/bioithome path=/home fstype=nfs

# Mounts for MasseyIFS
- name: Mount for masseyifs scratch
  mount: state=mounted src=chips:/scratch/masseyifs path=/scratch/masseyifs fstype=nfs

- name: Mount for masseyifs work
  mount: state=mounted src=chips:/work/masseyifs path=/work/masseyifs fstype=nfs

- name: Mount for masseyifs sequencing
  mount: state=mounted src=chips:/sequencing/masseyifs path=/sequencing/masseyifs fstype=nfs
