#!/bin/bash

# Script to auto build and install bamtools. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building SOAPdenovo2 ${VERSION} on ${DATE}"
cd /opt/bioit/SOAPdenovo2/src
wget https://github.com/aquaskyline/SOAPdenovo2/archive/r${VERSION}.tar.gz
mv r${VERSION}.tar.gz SOAPdenovo2-r${VERSION}.tar.gz
tar xvf SOAPdenovo2-r${VERSION}.tar.gz
cd SOAPdenovo2-r${VERSION}
make
mkdir /opt/bioit/SOAPdenovo2/${VERSION}/
mv SOAPdenovo-* /opt/bioit/SOAPdenovo2/${VERSION}/
echo "Writing modulefile"
echo "#%Module 1.0
#
#  SOAPdenovo2 module for use with 'environment-modules' package:
#
prepend-path  PATH           /opt/bioit/SOAPdenovo2/${VERSION}" > /opt/bioit/modulefiles/SOAPdenovo2/${VERSION}
