#!/bin/bash

# Script to auto build and install bamtools. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building FastQC ${VERSION} on ${DATE}"
cd /opt/bioit/FastQC/src
wget http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v${VERSION}.zip
unzip fastqc_v${VERSION}.zip
mv FastQC /opt/bioit/FastQC/${VERSION}
cd /opt/bioit/FastQC/${VERSION}
chmod 755 fastqc
echo "Writing modulefile"
echo "#%Module 1.0
#
#  FastQC module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/FastQC/${VERSION}" > /opt/bioit/modulefiles/FastQC/${VERSION}
