#!/bin/bash

# Script to auto build and install bamtools. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building IGV ${VERSION} on ${DATE}"
cd /opt/bioit/igv/src
wget https://github.com/igvteam/igv/archive/v${VERSION}.zip
mv v${VERSION}.zip igv-${VERSION}.zip
unzip igv-${VERSION}.zip
cd igv-${VERSION}
sed "s+@VERSION+${VERSION}+" --in-place src/resources/about.properties
sed "s+@TIMESTAMP+${DATE}+" --in-place src/resources/about.properties
sed "s+@BUILD+86+" --in-place src/resources/about.properties
sed "s+@DEVELOPMENT+false+" --in-place src/resources/about.properties
ant -Dinclude.libs=true
mkdir /opt/bioit/igv/${VERSION}
mv igv.jar /opt/bioit/igv/${VERSION}
mv lib /opt/bioit/igv/${VERSION}
cp ${HOME}/bioit/apps/igv/SPEC/igv /opt/bioit/igv/${VERSION}
echo "Writing modulefile"
echo "#%Module 1.0
#
#  igv module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/igv/${VERSION}/" > /opt/bioit/modulefiles/igv/${VERSION}
