#!/bin/bash

# Script to auto download and install igv. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Installing IGV ${VERSION} on ${DATE}"
cd /opt/bioit/igv/src
wget http://data.broadinstitute.org/igv/projects/downloads/2.4/IGV_${VERSION}.zip
unzip IGV_${VERSION}.zip
mv IGV_${VERSION} /opt/bioit/igv/${VERSION}
# Get rid of unwanted starters to not confuse the shell
rm /opt/bioit/igv/${VERSION}/igv.sh
rm /opt/bioit/igv/${VERSION}/igv.command
rm /opt/bioit/igv/${VERSION}/igv.bat
# Copy our own start up script
cp ${HOME}/bioit/apps/igv/SPEC/igv /opt/bioit/igv/${VERSION}
echo "Writing modulefile"
echo "#%Module 1.0
#
#  igv module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/igv/${VERSION}/" > /opt/bioit/modulefiles/igv/${VERSION}
