#!/bin/bash

# Script to auto download and install igv. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Installing IGV ${VERSION} on ${DATE}"
cd /opt/bioit/igv/src
wget http://data.broadinstitute.org/igv/projects/downloads/2.5/IGV_Linux_${VERSION}.zip
unzip IGV_Linux_${VERSION}.zip
mkdir /opt/bioit/igv/${VERSION}
mv IGV_Linux_${VERSION}/* /opt/bioit/igv/${VERSION}
# Rename startup script
mv /opt/bioit/igv/${VERSION}/igv.sh /opt/bioit/igv/${VERSION}/igv
# Fix bug with prefix
sed 's+prefix=`dirname $(readlink $0 || echo $0)`+prefix="$(dirname $(readlink -f $0))"+g' --in-place /opt/bioit/igv/${VERSION}/igv
echo "Writing modulefile"
echo "#%Module 1.0
#
#  igv module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/igv/${VERSION}/" > /opt/bioit/modulefiles/igv/${VERSION}
