#!/bin/bash

# Script to auto build and install bamtools. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building bbmap ${VERSION} on ${DATE}"
cd /opt/bioit/bbmap/src
wget https://downloads.sourceforge.net/project/bbmap/BBMap_${VERSION}.tar.gz
tar xvf BBMap_${VERSION}.tar.gz
mv bbmap ../${VERSION}
chmod 755 ../${VERSION}
cd ../${VERSION}
chmod -R 755 *
echo "Writing modulefile"
echo "#%Module 1.0
#
#  bbmap module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/bbmap/${VERSION}" > /opt/bioit/modulefiles/bbmap/${VERSION}
