#!/bin/bash

# Script to auto build and install ncbi-blast. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building rtg-tools ${VERSION} on ${DATE}"
cd /opt/bioit/rtg-tools/src
wget https://github.com/RealTimeGenomics/rtg-tools/releases/download/${VERSION}/rtg-tools-${VERSION}-linux-x64.zip
unzip rtg-tools-${VERSION}-linux-x64.zip
mv rtg-tools-${VERSION} /opt/bioit/rtg-tools/${VERSION}
echo n | /opt/bioit/rtg-tools/${VERSION}/rtg
echo "Writing modulefile"
echo "#%Module 1.0
#
#  rtg-tools module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/rtg-tools/${VERSION}" > /opt/bioit/modulefiles/rtg-tools/${VERSION}
