##
# Install python into all machines to start using ansible
# Ensures users/groups and munge is installed.
# Assumes you have done: ansible-galaxy install goozback.EPEL
##
- name: Setup ansible dependencies
  hosts: all
  tags: ['pre-deploy']
  gather_facts: no
  become: yes
  tasks:
    - name: Install python for ansible
      raw: sudo yum install python
      tags: ['centos']
    - name: Verify Ansible meets this playbook minimum version requirements.
      assert:
        that: "ansible_version.full | version_compare('2.4', '>=')"
        msg: >
          "You must update Ansible to at least 2.4 to use this playbook."

- name: Setup slurm
  hosts: slurm-controllers slurm-compute-nodes slurm-submit-hosts
  gather_facts: yes
  become: true
  roles:
    - goozbach.EPEL
  tasks:
    - include: tasks/slurm.yml
