##
# Install python into all machines to start using ansible
##
- name: Setup ansible dependencies
  hosts: all
  tags: ['pre-deploy']
  gather_facts: no
  become: yes
  tasks:
    - name: Install python for ansible
      raw: sudo yum install python
      tags: ['centos']

- name: Setup users
  hosts: all
  gather_facts: yes
  tags: ['users']
  become: yes
  vars_files:
    - vars/users.yml
  tasks:
    # Creates users from
    - include: tasks/setup-users-and-group.yml

    # Allows sudo for created users without passwords
    - include: tasks/allow-sudo.yml

# This is just a small best practise for all ssh connections
- name: Setup SSH Security hardening
  hosts: all
  tags: ['security']
  become: yes
  tasks:
    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PermitRootLogin"
                  line="PermitRootLogin no"
                  state=present
      notify: restart sshd

    - name: Disallow password SSH access
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present
      notify: restart sshd
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
