#!/bin/bash

if [ ! -e good_dataset.fq.bz2 ]; then
	echo 'No test data.'
	exit 1
fi

output='good_dataset.fq.matrix.pdf'

set -e
module load SolexaQA++
module load R

function cleanup() {
	for file in good_dataset.fq.hist.pdf good_dataset.fq.matrix \
		good_dataset.fq.png good_dataset.fq.quality good_dataset.fq \
		good_dataset.fq.quality.pdf good_dataset.fq.segments \
		good_dataset.fq.cumulative.pdf good_dataset.fq.matrix.pdf \
		good_dataset.fq.segments_cumulative.pdf good_dataset.fq.segments_hist.pdf; do
		[ -e ${file} ] && rm -f ${file}
	done
	return 0
}

cleanup

bzcat good_dataset.fq.bz2 > good_dataset.fq
SolexaQA++ analysis good_dataset.fq
if [ ! -e ${output} ]; then
	echo "${output} not found"
	false # trigger error, exit
fi
#if ! file ${output} | grep -q PNG; then
#	echo "${output} is not a PNG"
#	false # trigger error, exit
#fi

cleanup
exit 0
