#!/bin/bash

# Script to auto build and install bamtools. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building bamtools ${VERSION} on ${DATE}"
cd /opt/bioit/bamtools/src
wget https://github.com/pezmaster31/bamtools/archive/v${VERSION}.tar.gz
tar xvf v${VERSION}.tar.gz
cd bamtools-${VERSION}
mkdir build
cd build
cmake3 -DCMAKE_INSTALL_PREFIX:PATH=/opt/bioit/bamtools/${VERSION} ..
make all
make install
echo "Copy bamtools script"
cd /opt/bioit/bamtools/${VERSION}
cp ${HOME}/bioit/apps/bamtools/SPEC/bamtools /opt/bioit/bamtools/${VERSION}/
echo "Writing modulefile"
echo "#%Module 1.0
#
#  bamtools module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/bamtools/${VERSION}" > /opt/bioit/modulefiles/bamtools/${VERSION}
echo "Writing module .version to set default"
echo "#%Module1.0
##
##  The desired version of bamtools
##
set ModulesVersion ${VERSION}" > /opt/bioit/modulefiles/bamtools/.version
