#!/bin/bash

# Script to auto build and install bamtools. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
echo "Building hisat2 ${VERSION}"
cd /opt/bioit/hisat2/src
wget ftp://ftp.ccb.jhu.edu/pub/infphilo/hisat2/downloads/hisat2-${VERSION}-source.zip
unzip hisat2-${VERSION}-source.zip
cd hisat2-${VERSION}
make
mv scripts /opt/bioit/hisat2/${VERSION}/
mv doc /opt/bioit/hisat2/${VERSION}/
mv example /opt/bioit/hisat2/${VERSION}/
mv hisatgenotype_scripts /opt/bioit/hisat2/${VERSION}/
mv hisatgenotype_modules /opt/bioit/hisat2/${VERSION}/
mkdir /opt/bioit/hisat2/${VERSION}/bin
mv hisat2 /opt/bioit/hisat2/${VERSION}/bin/
mv hisat2-* /opt/bioit/hisat2/${VERSION}/bin/
mv *.py /opt/bioit/hisat2/${VERSION}/bin/
cd /opt/bioit/hisat2/${VERSION}/bin 
find . -type f -name '*genotype*.py' | xargs sed "/ sys,/a sys.path.append('/opt/bioit/hisat2/${VERSION}/hisatgenotype_modules')" --in-place
echo "Writing modulefile"
echo "#%Module 1.0
#
#  hisat2 module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/hisat2/${VERSION}/bin" > /opt/bioit/modulefiles/hisat2/${VERSION}
