#!/bin/bash

# Script to auto build and install bamtools. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
echo "Building htslib ${VERSION}"
cd /opt/bioit/htslib/src
wget https://github.com/samtools/htslib/releases/download/${VERSION}/htslib-${VERSION}.tar.bz2
tar xvf htslib-${VERSION}.tar.bz2
cd htslib-${VERSION}
./configure --prefix=/opt/bioit/htslib/${VERSION}
make
make install
echo "Writing modulefile"
echo "#%Module 1.0
#
#  htslib module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/htslib/${VERSION}/bin
prepend-path  MANPATH           /opt/bioit/htslib/${VERSION}/share/man" > /opt/bioit/modulefiles/htslib/${VERSION}
