#!/bin/bash

# Script to auto build and install bamtools. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
echo "Building bedtools2 ${VERSION}"
cd /opt/bioit/bedtools2/src
tar xvf bedtools-${VERSION}.tar.gz
mv bedtools2 bedtools-${VERSION}
cd bedtools-${VERSION}
sed "s#prefix ?= /usr/local#prefix ?= /opt/bioit/bedtools2/${VERSION}#g" --in-place /opt/bioit/bedtools2/src/bedtools-${VERSION}/Makefile
make 
make install
echo "Writing modulefile"
echo "#%Module 1.0
#
#  bedtools2 module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/bedtools2/${VERSION}/bin" > /opt/bioit/modulefiles/bedtools2/${VERSION}
