#!/bin/bash

# Script to auto build and install ncbi-blast. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building ncbi-blast ${VERSION} on ${DATE}"
cd /opt/bioit/ncbi-blast/src
wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/${VERSION//+}/ncbi-blast-${VERSION}-x64-linux.tar.gz
tar xvf ncbi-blast-${VERSION}-x64-linux.tar.gz
mv ncbi-blast-${VERSION} /opt/bioit/ncbi-blast/${VERSION}
echo "Writing modulefile"
echo "#%Module 1.0
#
#  ncbi-blast module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/ncbi-blast/${VERSION}/bin" > /opt/bioit/modulefiles/ncbi-blast/${VERSION}
