#!/bin/bash

# Script to auto build and install bcftools. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building bcftools ${VERSION} on ${DATE}"
cd /opt/bioit/bcftools/src
wget https://github.com/samtools/bcftools/releases/download/${VERSION}/bcftools-${VERSION}.tar.bz2
tar xvf bcftools-${VERSION}.tar.bz2
cd bcftools-${VERSION}
./configure --prefix=/opt/bioit/bcftools/${VERSION}
make -j8
make install
echo "Writing modulefile"
echo "#%Module 1.0
#
#  bcftools module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/bcftools/${VERSION}/bin
prepend-path  MANPATH           /opt/bioit/bcftools/${VERSION}/share/man" > /opt/bioit/modulefiles/bcftools/${VERSION}
echo "Writing module .version to set default"
echo "#%Module1.0
##
##  The desired version of bcftools
##
set ModulesVersion ${VERSION}" > /opt/bioit/modulefiles/bcftools/.version
