#!/bin/bash

# Script to auto build and install hmmer. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building hmmer ${VERSION} on ${DATE}"
cd /opt/bioit/hmmer/src
wget http://eddylab.org/software/hmmer3/${VERSION}/hmmer-${VERSION}-linux-intel-x86_64.tar.gz
tar xvf hmmer-${VERSION}-linux-intel-x86_64.tar.gz
mv hmmer-${VERSION}-linux-intel-x86_64/binaries /opt/bioit/hmmer/${VERSION}
echo "Writing modulefile"
echo "#%Module 1.0
#
#  hmmer module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/hmmer/${VERSION}" > /opt/bioit/modulefiles/hmmer/${VERSION}
