#!/bin/bash

# Script to auto build and install hmmer. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building hmmer ${VERSION} on ${DATE}"
cd /opt/bioit/hmmer/src
wget http://eddylab.org/software/hmmer/hmmer-${VERSION}.tar.gz
tar xvf hmmer-${VERSION}.tar.gz
cd hmmer-${VERSION}
./configure --prefix=/opt/bioit/hmmer/${VERSION}
make
make install
cd easel
make install
echo "Writing modulefile"
echo "#%Module 1.0
#
#  hmmer module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/hmmer/${VERSION}/bin
prepend-path  MANPATH           /opt/bioit/hmmer/${VERSION}/share/man" > /opt/bioit/modulefiles/hmmer/${VERSION}
echo "Writing module .version to set default"
echo "#%Module1.0
##
##  The desired version of hmmer
##
set ModulesVersion ${VERSION}" > /opt/bioit/modulefiles/hmmer/.version
