#!/bin/bash
set -e

# Script to auto build and install cutadapt. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building cutadapt ${VERSION} on ${DATE}"
# Get the source so we have the changes
cd /opt/bioit/cutadapt/src
wget https://github.com/marcelm/cutadapt/archive/v${VERSION}.tar.gz
mv v${VERSION}.tar.gz cutadapt-${VERSION}.tar.gz
tar xvf cutadapt-${VERSION}.tar.gz
# Actual install is done from pip in venv
mkdir -p /opt/bioit/cutadapt/${VERSION}
# Handle differences between Rocky and CentOS
if [ $(cat /etc/redhat-release | grep -ci "rocky") -eq 1 ]; then
  # Rocky Linux
  /usr/bin/python3.8 -m venv /opt/bioit/cutadapt/${VERSION}/venv
else
  # CentOS Linux
  /opt/rh/rh-python38/root/usr/bin/python -m venv /opt/bioit/cutadapt/${VERSION}/venv
fi
# Need to upgrade pip for install to work
/opt/bioit/cutadapt/${VERSION}/venv/bin/pip3 install --upgrade pip
/opt/bioit/cutadapt/${VERSION}/venv/bin/pip3 install cutadapt==${VERSION}
# Move the cutadapt bin to the normal location
mv /opt/bioit/cutadapt/${VERSION}/venv/bin/cutadapt /opt/bioit/cutadapt/${VERSION}
echo "Writing modulefile"
echo "#%Module 1.0
#
#  cutadapt module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/cutadapt/${VERSION}" > /opt/bioit/modulefiles/cutadapt/${VERSION}
echo "Writing module .version to set default"
echo "#%Module1.0
##
##  The desired version of cutadapt
##
set ModulesVersion ${VERSION}" > /opt/bioit/modulefiles/cutadapt/.version
