#!/bin/bash

# Script to auto build and install stringtie Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building stringtie ${VERSION} on ${DATE}"
cd /opt/bioit/stringtie/src
wget http://ccb.jhu.edu/software/stringtie/dl/stringtie-${VERSION}.tar.gz
tar xvf stringtie-${VERSION}.tar.gz
cd stringtie-${VERSION}
make release
mkdir /opt/bioit/stringtie/${VERSION}
mv stringtie /opt/bioit/stringtie/${VERSION}/
echo "Writing modulefile"
echo "#%Module 1.0
#
#  stringtie module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/stringtie/${VERSION}" > /opt/bioit/modulefiles/stringtie/${VERSION}
