#!/bin/bash
set -e

# Script to auto build and install multiqc. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building multiqc ${VERSION} on ${DATE}"
# Iinstall from pip in venv
mkdir -p /opt/bioit/multiqc/${VERSION}
# Rocky Linux
/usr/bin/python3.11 -m venv /opt/bioit/multiqc/${VERSION}/venv
# Need to upgrade pip for install to work
/opt/bioit/multiqc/${VERSION}/venv/bin/pip3 install --upgrade pip
/opt/bioit/multiqc/${VERSION}/venv/bin/pip3 install multiqc==${VERSION}
# Move the multiqc bin to the normal location
mv /opt/bioit/multiqc/${VERSION}/venv/bin/multiqc /opt/bioit/multiqc/${VERSION}
echo "Writing modulefile"
echo "#%Module 1.0
#
#  multiqc module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/multiqc/${VERSION}" > /opt/bioit/modulefiles/multiqc/${VERSION}
echo "Writing module .version to set default"
echo "#%Module1.0
##
##  The desired version of multiqc
##
set ModulesVersion ${VERSION}" > /opt/bioit/modulefiles/multiqc/.version
