#!/bin/bash

# Script to auto build and install bamtools. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
echo "Building picard ${VERSION}"
cd /opt/bioit/picard/src
git clone -b ${VERSION} https://github.com/broadinstitute/picard.git
mv picard picard-${VERSION}
cd picard-${VERSION}
./gradlew shadowJar
mkdir /opt/bioit/picard/${VERSION}
mv build/libs/picard.jar /opt/bioit/picard/${VERSION}
echo "Copy picard script"
cp ${HOME}/bioit/apps/picard/SPEC/picard /opt/bioit/picard/${VERSION}
echo "Writing modulefile"
echo "#%Module 1.0
#
#  picard module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/picard/${VERSION}" > /opt/bioit/modulefiles/picard/${VERSION}
