# These users will be created into all servers
# All users with state: present will be created and state absent will be deleted
bioit_admin_list:
  - name: "Shane Sturrock"
    username: "sss"
    uid: 1000
    groups:
      - wheel
      - bioit_admin
      - vboxusers
    keys:
      active:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC34jhmDu4DO2iGthqK9kEoJvt3Rzolmu8HeCJtcvPlkjwSFyqXk1lGLQTWMZbAbVl3AufgF3+hTwxwJSmdrY8X8WJrp9Y+i1z/GFKkXYeAmmxJrl+/JL9c3DUGiPJHKLCt2cvB/JZb4ZDsXnq5gvJKyGHJ1nkEOPoKw5GsipZT9Th6jBI7jomtjdxFPCmfdeDxnZaUCQyEE2grPxzfE/GS0x/14tN/rrRFfkTr1tIaWRdXYMnsaVmxqta0MC30CDt6SdFqO+43MRlChkP+LhTwK2t5KbZuh6iMHlvpyxorGfILH1nwGPFBcVH+lzl7C9lK8SBEVX9MFU/vK050TLRR sss@Shanes-MBP" 
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC68bprlFK0Lyoy5Rp/Q4cEGBJTIZ+x9yJksAv6e8zJznuyPGzRAjonolCtc5r8+5v6r8Y72XWMVrxaM35Zrmlevu2InpVqyVHIgayaxqnEPIcLzMNldleg0UwMM0M5YNngCtRLOuuFWFk4PcAt9xeeARUyZ4+QtdK3AyaFCwC34miTUyF1ZiS1rmJl0p524tPfQEMQPcK6TJTYstn/j+yvhNE8uW5K+YFbYLLhkf2cVF/ti8+E46UVEIUiDofasblpxoMsglIPOiTLUO4441UivjMRZXuIAXtHVUen4Xvqg14g4Rf9JjXAda5IcW2dsQW21cgUQ5RfeBGSp2G+2uHR shane@bfc.scionresearch.com"
    shell: "/bin/bash"
    state: present

# This is the admin group where we will add users with sudo access
admin_group: bioit_admin
