#!/bin/bash

# Script to auto build and install velvet. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building velvet ${VERSION} on ${DATE}"
cd /opt/bioit/velvet/src
#wget https://www.ebi.ac.uk/~zerbino/velvet/velvet_${VERSION}.tgz
wget https://github.com/dzerbino/velvet/archive/refs/tags/v${VERSION}.tar.gz
mv v${VERSION}.tar.gz velvet_${VERSION}.tgz
tar xvf velvet_${VERSION}.tgz
cd velvet-${VERSION}
#cd velvet_${VERSION}
# Tweak makefile
sed 's+CATEGORIES=2+CATEGORIES=99+g' --in-place Makefile
sed 's+MAXKMERLENGTH=31+MAXKMERLENGTH=255+g' --in-place Makefile
make 'OPENMP=8'
# Fix perl shebangs
find . -type f -name '*.pl' | xargs sed 's=/usr/local/bin/perl=/usr/bin/perl=g' --in-place
mkdir /opt/bioit/velvet/${VERSION}
mv velveth /opt/bioit/velvet/${VERSION}
mv velvetg /opt/bioit/velvet/${VERSION}
mv contrib /opt/bioit/velvet/${VERSION}
echo "Writing modulefile"
echo "#%Module 1.0
#
#  velvet module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/velvet/${VERSION}" > /opt/bioit/modulefiles/velvet/${VERSION}
echo "Writing module .version to set default"
echo "#%Module1.0
##
##  The desired version of velvet
##
set ModulesVersion ${VERSION}" > /opt/bioit/modulefiles/velvet/.version
