#!/bin/bash
set -e

# Script to auto build and install ea-utils Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building ea-utils ${VERSION} on ${DATE}"
cd /opt/bioit/ea-utils/src
wget https://github.com/ExpressionAnalysis/ea-utils/archive/${VERSION}.tar.gz
mv ${VERSION}.tar.gz ea-utils-${VERSION}.tar.gz
tar xvf ea-utils-${VERSION}.tar.gz
cd ea-utils-${VERSION}/clipper
export PERL5LIB=`pwd`
sed "s+PREFIX?=/usr+PREFIX?=/opt/bioit/ea-utils/${VERSION}+g" --in-place Makefile
make
make install
echo "Writing modulefile"
echo "#%Module 1.0
#
#  ea-utils module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/ea-utils/${VERSION}/bin" > /opt/bioit/modulefiles/ea-utils/${VERSION}
echo "Writing module .version to set default"
echo "#%Module1.0
##
##  The desired version of ea-utils
##
set ModulesVersion ${VERSION}" > /opt/bioit/modulefiles/ea-utils/.version
