#!/bin/bash

# Script to auto build and install bismark. Just provide the version

function usage() {
 cat << EOF
Usage: ${0} <VERSION>

 <VERSION> is the specific version number you're building

EOF
}

# Quit the script if it doesn't have enough flags set
if [ $# -lt 1 ]; then
 usage
 exit 1
fi

VERSION=$1
DATE=`date +"%d/%m/%Y %r"`
echo "Building bismark ${VERSION} on ${DATE}"
cd /opt/bioit/bismark/src
wget https://github.com/FelixKrueger/Bismark/archive/${VERSION}.tar.gz
mv ${VERSION}.tar.gz bismark-${VERSION}.tar.gz
tar xvf bismark-${VERSION}.tar.gz
mv Bismark-${VERSION} /opt/bioit/bismark/${VERSION}
echo "Writing modulefile"
echo "#%Module 1.0
#
#  bismark module for use with 'environment-modules' package:
#
prepend-path  PATH              /opt/bioit/bismark/${VERSION}" > /opt/bioit/modulefiles/bismark/${VERSION}
echo "Writing module .version to set default"
echo "#%Module1.0
##
##  The desired version of bismark
##
set ModulesVersion ${VERSION}" > /opt/bioit/modulefiles/bismark/.version
